my_list=[1,2,3,4]
# print("element at index[0]:",my_list[0])
# my_list[1]=78
# print("changed list:",my_list)
# my_list.append(8)
# print("list after appending:",my_list)
# my_list.insert(1,'a')
# print("list after inserting:",my_list)
# my_list.extend([5,6])
# print("list after extending:",my_list)
# my_list.remove('a')
# print("list after removing:",my_list)
my_copy_list=my_list.copy()
# print(my_copy_list)
# my_list.clear()
# print("initial list:",my_list)
# print(my_copy_list)
# print("index of [3] in the list",my_list.index(3))
my_copy_list.sort()
print(my_copy_list)
my_copy_list.reverse()
print(my_copy_list)
print(my_copy_list[1])
